spring.application.name=SpringBootLoggingProj01

#change the logger level specific each package
#logging.level.com.mainapp.rest=TRACE
#logging.level.com.mainapp=TRACE

#change teh logger level for entire project
logging.level.root=TRACE

#Taking file as the destination
#logging.file.name=App.log

#Taking size based rolling policy file as the destination
logging.file.name=App.log
logging.logback.rollingpolicy.file-name-pattern=App-%d(yyyy-MM-dd).%i.log
logging.logback.rollingpolicy.max-file-size=1MB
logging.logback.rollingpolicy.max-history=10
logging.logback.rollingpolicy.total-size-cap=10MB
logging.logback.rollingpolicy.clean-history-on-start=true